### ISSUE TITLE
Error when using with grunt "Unexpected rule type "rule"; looking for module header"

### ISSUE THREAD

**Issue by esr360** [oddbird/true#60] opened 2016-07-17 18:55 UTC
I'm still unsure if this is an error with my code, but I believe I have everything set up correctly.

I'm trying to run tests using Mocha and Grunt, but I'm getting an error. Here is the relevant information generated on the terminal:

```
Running "mochacli:all" (mochacli) task
/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/sass/true/_messages.scss:28 DEBUG: 1 Tests, 1 Passed, 0 Failed
/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:62
  throw new Error(
  ^

Error: Line 2, column 1: Unexpected rule type "rule"; looking for module header
    at parseError (/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:62:9)
    at parseModule (/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:83:3)
```

It appears from line 2 as though the tests were run and passed, but I can't figure out why this might be happening.

**Comment by carljm** [comment] 2016-07-17 19:03
Can you paste the full CSS output from the tests?

**Comment by esr360** [comment] 2016-07-17 19:14
Thanks for the swift reply. I couldn't actually find a generated CSS file anywhere, but when running the tests manually I get the following output:

```css
/* # Module: breakpoint */
/* -------------------- */
/* Test: should return the appropriate breakpoint value based on the passed key */
/*   ✔  */
/*  */
/*  */
/* # SUMMARY ---------- */
/* 1 Tests: */
/*  - 1 Passed */
/*  - 0 Failed */
/* -------------------- */
```

**Comment by mirisuzanne** [comment] 2016-07-17 19:17
Can you also paste the `breakpoint`-module tests?

**Comment by esr360** [comment] 2016-07-17 19:18
Sure:

```scss
@include test-module('breakpoint') {
  @include test('should return the appropriate breakpoint value based on the passed key') {

    $actual   : kgs-breakpoint('break-3');
    $expected : 940px;

    @include assert-equal($actual, $expected);

  }
}
```

**Comment by mirisuzanne** [comment] 2016-07-18 01:39
@carljm did you already address this issue in one of the other branches I merged? I can't reproduce this on master.

**Comment by carljm** [comment] 2016-07-19 16:18
@mirisuzanne With the given output CSS, I can reproduce a failure to parse in earlier versions of true (specifically in 2e51a891a1, the last version before this week's merges), though the error I get is different: `Error: Line 4, column 1: Unexpected comment "✔"; looking for module header`.

With latest master, this output CSS successfully parses, but the test has no pass/fail status.

The problem in both cases is that the line with the checkmark is lacking a text description following the checkmark, and the parser expects one there.

If this should be supported, I can fix the parser to accept it. Why is the output CSS lacking a description there?

**Comment by mirisuzanne** [comment] 2016-07-19 16:30
@carljm Yeah, I figured that was the problem. I did add default descriptions yesterday, as a fix for this specific case (5870fe0173e3221).

- This solution still allows you to override the default with an empty message, which we should not allow if that breaks the parser.
- There is probably a better default to use. Maybe the test description should be used, if no assertion description is passed in?

**Comment by carljm** [comment] 2016-07-19 16:53
Your call on the best default description, and on whether to allow or disallow empty. It'd certainly be possible to fix the parser to allow an empty description, if you prefer that.

**Comment by mirisuzanne** [comment] 2016-07-20 18:49
@carljm I'd love to solve it on both ends :)

**Comment by carljm** [comment] 2016-07-21 00:20
@mirisuzanne Alrighty then! Parser end is solved in #62.

**Comment by mirisuzanne** [comment] 2016-07-21 17:57
Defaults added in 1254903

**Closed by mirisuzanne** 2016-07-21 17:57 UTC
Labels: bug

**Comment by esr360** [comment] 2016-08-11 00:47
So with the latest version (2.1.3) I'm now getting the following:

```
/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/sass/true/_messages.scss:28 DEBUG: 1 Tests, 1 Passed, 0 Failed
/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:114
  throw parseError('Unexpected rule type "' + rule.type + '"', 'module header', rule.position);
  ^

Error: Line 2, column 1: Unexpected rule type "rule"; looking for module header
    at parseError (/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:89:10)
    at parseModule (/Users/esr360/Sites/One Nexus/source/assets/vendor/Kayzen-GS/node_modules/sass-true/lib/main.js:114:9)
    ...
```

**Comment by mirisuzanne** [comment] 2016-08-12 17:18
061b331 fixes a bug in the default assertion messages.

**Comment by carljm** [comment] 2016-08-17 06:36
@esr360 can you a) open a new issue, since this seems like a different problem, and b) provide a minimal reproduction case? Thanks.

**Comment by ProgrammingJoe** [comment] 2017-01-30 16:58
I am still getting this error message:

```
throw parseError('Unexpected rule type "' + rule.type + '"', 'module header', rule.position);
Error: Line 5, column 1: Unexpected rule type "rule"; looking for module header
```

Was another issue created? Is this going to be fixed?

**Comment by sir-dunxalot** [comment] 2017-02-01 00:59
I am also still getting this error:

```
/project-path/node_modules/sass-true/lib/main.js:114
  throw parseError('Unexpected rule type "' + rule.type + '"', 'module header', rule.position);
  ^

Error: Line 125, column 1: Unexpected rule type "rule"; looking for module header
    at parseError (/project-path/node_modules/sass-true/lib/main.js:89:10)
```

Node version: `6.9.2`
Sass-true version: `^2.1.4`

The only assert helper used in tests is assert-equal and it's used as follows:

```
@include test-module('Function: namespacing/namespace with namespace') {

  @include test('Should namespace a selector') {
    $actual: namespace('button');
    $expected: #{peacock}#{$wordSeperator}#{button};

    @include assert-equal($actual, $expected);
  }
}
```

You can view the [full test suite here](https://github.com/sir-dunxalot/compass-boilerplate/tree/master/tests).

**Comment by sir-dunxalot** [comment] 2017-02-01 01:03
I have been able to work around the issue by capping the `sass-true` version to `2.0.3`.

**Comment by mirisuzanne** [comment] 2017-02-01 03:45
@carljm are these all different issues that result in a similar error message? If so, we should rename this issue, and open new ones. I'm not sure how to track these down, since the error is coming from Mocha.

@sir-dunxalot can you do a manual sass compile of the tests (not through mocha) and paste the resulting CSS output? That might help give me some more clues to work with.

**Comment by carljm** [comment] 2017-02-01 17:37
Hard to tell if they are the same or different issues without seeing the CSS output. Probably what we need to do is add instructions to that error message for how to generate and see the CSS output, since that will probably make the issue a lot clearer in most cases.

**Comment by mirisuzanne** [comment] 2017-02-01 17:42
Good call. As I understand, that error is the parser choking on the output. Any way for it to automatically print the lines around where it failed?

**Comment by carljm** [comment] 2017-02-01 17:52
Yeah, actually, that should be possible too.
