### ISSUE TITLE
Multiline comments break tests

### ISSUE THREAD

**Issue by weaintplastic** [oddbird/true#55] opened 2016-07-08 08:18 UTC
Hi,
since updating to version 2.1.0 my tests are failing.

The reason for this are multiline comments that I'm using to document my functions and mixins that I'm about to test.

For a function like this:
```
/**
 * Shifts a color by given steps in its shading group.
 */
@function color-shift($color, $amount) {
...
}
```

and executing a test like this:
```
@include test('is shifting a giving color by a given amount') {
    $test: color-shift(#034AA4, 2);
    $expect: #034AA6;
    @include assert-equal($test, $expect, 'Returns the color code of the requested color');
  }
```

will result in the following error:
```
Error: Line 2, column 1: Unexpected comment "*
 * Shifts a color by given steps in its shading group."; looking for module header
    at parseError (/Users/loesslein/Workspace/nova/node_modules/sass-true/lib/main.js:62:9)
...
```

Hope you can find a way not forcing me to put '# Module: ' in my comments.

**Comment by mirisuzanne** [comment] 2016-07-08 17:11
Hi @weaintplastic - thanks for posting this. I made a minor release, when it should have been major in retrospect. That's my mistake.

You certainly shouldn't be putting `# Module` in you comments, as that will confuse the parser. I think we have to make two changes here:

1. Meaningful comments (created by True, and used by the parser) should be marked explicitly. @carljm would it work to add the maker to the ends of lines? I'm imagining something simple like `* * * * ` before the final `*/` comment-closing marker.
2. Un-marked comments should be ignored by the parser, and treated as CSS for the purposes of output assertions.

In the meantime, your best option is to either downgrade while we sort this out, or use silent `//` Sass comments instead. We'll try to get a new release out ASAP.

**Comment by carljm** [comment] 2016-07-08 17:19
Yeah, we can ignore all comments that don't have a certain marker at the end of lines.

Regarding un-marked comments "treated as CSS for the purposes of output assertions", I'll have to look at how feasible that is. I was thinking we'd just ignore them. Do we really want to make people include loud comments in their asserted output?

**Comment by mirisuzanne** [comment] 2016-07-08 18:19
What I meant is that currently our output comparison tests compare *everything* inside the `/*   OUTPUT   */` and `/*   EXPECTED   */` blocks, including loud comments. That means you can test loud comment output, if you need to. Say, hypothetically, you are building a tool that outputs meaningful comments, and you want to test that...

I was not proposing a new feature, only that output comparisons should continue to work in the same way the do currently — with comments included in the comparison.

**Comment by carljm** [comment] 2016-07-16 22:45
I didn't implement the end-line marker at this point; it may be a good idea, but it's not strictly necessary to fix this. That's really a fix for a separate (still-hypothetical) problem: people with their own loud comments whose structure matches something we use and parse.

**Closed** 2016-07-18 01:16 UTC

**Comment by weaintplastic** [comment] 2016-08-05 09:24
Hey. So sorry not being able to update the package until today.
With version 2.1.2 and the scenario above it is still failing with the same error message.

**Comment by mirisuzanne** [comment] 2016-08-05 16:30
Looks like I didn't do a release of this fix. I can confirm that 2.1.2 fails for me as well, but 2.1.3 works.
