### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by borisdamevin** [oddbird/true#229] opened 2022-04-06 18:48 UTC
Hi,

I don't if is possible, but can we have code coverage with sass file?

Works with us files, so way not with sass!

Thank you.

**Comment by mirisuzanne** [comment] 2022-06-13 15:53
Hi @borisdamevin - closing this as a duplicate of #88. I think we're still open to this feature, but haven't had a chance to prioritize it on our end.

**Closed by mirisuzanne** 2022-06-13 15:53 UTC
